rbtname: L03A

system: # 机器人系统参数
  GRAV: -9.8    # 重力加速度
  TSf: 0.002   # time step in float
  Tend: 1000   # 测试时间 second
  root_path: ".."
  mjcf_path: "/resources/robots/cart/inverted_pendulum.xml"
  log_path: &log_path
    dir: ../log/cartpole1/${now:%Y-%m-%d}/${now:%H-%M-%S}
  visual: True    #  False   True
  dynamics_randomization: False

trainer:
  policy: "MlpPolicy"
  n_steps: 512
  batch_size: 256
  pi_net_arch: [256, 256]
  vf_net_arch: [256, 256]
  device: "cpu"

  n_eval_episodes: 10

env:
  num_envs: 8
  state_buffer_size: 1
  time_limit: 600  # 最大600个step

commands:
  lin_vel_x:        [0.6, 0.6]
  lin_vel_y:        [0.0, 0.0]
  ang_vel_yaw:      [-1.0, 1.0]
  ang_vel_roll:      [0.0, 0.0]

init_state:
  pos: [0.0, 0.0, 0.1]
#  default_left_joint_angles:  [0.1 , 0.0, 1.0, -1.8, 1.57, -1.57]
#  default_right_joint_angles: [-0.1, 0.0, 1.0, -1.8, 1.57, -1.57]
  default_left_joint_angles:  [0.0, 0.0, 0.0, 0.0]
  default_right_joint_angles: [0.0, 0.0, 0.0, 0.0]

control:
  # PD Drive parameters:
  P: [350, 400, 500, 300]
  D: [ 8,  10,  20,  5]
  # action scale: target angle = actionScale * action + defaultAngle
  action_scale: 0.5
  # decimation: Number of control action updates @ sim DT per policy DT
  decimation: 50
  # period: counter of dt, period_t = period * dt, 20 * 0.02 = 0.4
  period: 20

rewards:
  omega: 0.5
  scales:
    ref:    0.1
    spring: 0.1
    ori:    0.1
    vel:    0.1
    termin: 0.1

hydra:
  run:
    <<: *log_path
